name: Shareapp workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.13
